// Generated by CoffeeScript 1.4.0
(function() {
  var TCPConnection, Table, XbmcApi, config, connection, table, xbmcApi, _ref;

  Table = require('cli-table');

  _ref = require('..'), TCPConnection = _ref.TCPConnection, XbmcApi = _ref.XbmcApi;

  config = require('./config');

  connection = new TCPConnection({
    host: config.connection.host,
    port: config.connection.port,
    verbose: true
  });

  xbmcApi = new XbmcApi({
    silent: false,
    connection: connection
  });

  xbmcApi.media.songs({
    //properties: ['genre', 'year']
    "filter":{"artistid":4} 
  });

  
  table = new Table({
    head: ['#', 'Label']
  });
  
  table.options.style.compact = true;

  xbmcApi.on('api:songs', function(songs) {
    var song, _i, _len;
    console.log("" + songs.length + " songs");
    for (_i = 0, _len = songs.length; _i < _len; _i++) {
      song = songs[_i];
      table.push([song.label]);
    }
    return console.log(table.toString());
  });

}).call(this);
